### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by chy-causer**
Thanks for the tool!

### CODE REVIEW

**Comment by genivia-inc** [comment]
Thanks.

**Comment by chy-causer** [comment]
Did you spot the typo? No worries if it's intentional and a test for fuzzy searching :)

It's probably faster if you fix it yourself rather than merge.

**Comment by genivia-inc** [comment]
The README was merged. Not sure why the typo is still there.

**Comment by genivia-inc** [comment]
I will commit an updated README.

**Pull request closed without merging**
