### PR TITLE
README.md: add FreeBSD installation instructions

### PR DESCRIPTION
**Pull request by emaste**

### CODE REVIEW

**Comment by genivia-inc** [comment]
@emaste thank you again for contributing to the ugrep project. I made a recent improvement v4.3.1-1 which is not yet released, because the changes rely on not-so-portable API calls. Therefore, I don't know for sure if ugrep still builds on FreeBSD. See #305 for details. Is it possible for you to clone ugrep v4.3.1-1 from the repo and execute `./build.sh`? That would be very helpful for all of us!

**Comment by genivia-inc** [comment]
I've also posted this question on r/freebsd [What is the right way to set thread affinity on FreeBSD with cpuset_setaffinity?](https://www.reddit.com/r/freebsd/comments/17dj0wl/what_is_the_right_way_to_set_thread_affinity_on/)

**Comment by emaste** [comment]
> Is it possible for you to clone ugrep v4.3.1-1 from the repo and execute `./build.sh`? That would be very helpful for all of us!

I don't see a tag or branch for v4.3.1-1, can you clarify?

**Comment by genivia-inc** [comment]
Thank you for your follow up. The v4.3.1-1 update is not a release or tagged. Use `git clone https://github.com/Genivia/ugrep` to download, then `./build.sh`. Thanks!

**Pull request merged**
